name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: |
          echo build project
          npm install
          npm run build

      - name: deploy cms
        run: |
          echo deploy cms
          SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" npm run deploy

      - name: deploy prod
        run: |
          aws s3 sync ./packages/react/build/js s3://${{ secrets.AWS_S3_BUCKET }}/js --delete
          aws s3 sync ./packages/react/build/css s3://${{ secrets.AWS_S3_BUCKET }}/css --delete
          aws s3 cp ./packages/react/build/index.html s3://${{ secrets.AWS_S3_BUCKET }}/
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'

#      - name: deploy prod
#        run: |
#          echo trigger prod deploy
#          git push -f origin origin/main:production
